addons:
  hosts:
  - node1
before_cache:
- rm -rf $HOME/CACHE; find $TRAVIS_BUILD_DIR -name .starts | while read line; do du
  -sh $line;         DIR=$(dirname $HOME/CACHE$line); mkdir -p $DIR; cp -r $line $DIR;
  done
- find $TRAVIS_BUILD_DIR -name jdeps-cache | while read line; do du -sh $line;         DIR=$(dirname
  $HOME/CACHE$line); mkdir -p $DIR; cp -r $line $DIR; done
- echo CACHESIZE $(du -sk $HOME/CACHE)
before_install:
- find $HOME/CACHE -name jdeps-cache | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#jdeps-cache/} ]]; then cp -r $line $DIR; fi;
  done
- find $HOME/CACHE -name .starts | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.starts/} ]]; then cp -r $line $DIR; fi; done
- rvm use 2.1.5 --install
- nvm install 0.12.2
- nvm use 0.12.2
before_script:
- find $TRAVIS_BUILD_DIR -name .starts | while read line; do rm -rf $line; done
- find $TRAVIS_BUILD_DIR -name jdeps-cache | while read line; do rm -rf $line; done
- find $HOME/CACHE -name jdeps-cache | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#jdeps-cache/} ]]; then cp -r $line $DIR; fi;
  done
- find $HOME/CACHE -name .starts | while read line; do du -sh $line;         DIR=$(dirname
  ${line#$HOME/CACHE}); if [[ -d ${DIR#.starts/} ]]; then cp -r $line $DIR; fi; done
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.rvm
  - $NVM_DIR
  - $HOME/CACHE
dist: trusty
env:
- MODULES=storm-client
- MODULES=storm-server
- MODULES=storm-core
- MODULES='!storm-client,!storm-server,!storm-core'
- MODULES='INTEGRATION-TEST'
install: /bin/bash ./dev-tools/travis/travis-install.sh `pwd`
jdk:
- oraclejdk8
language: java
script:
- touch NOW
- echo GIBSTUDYSTART $(date)
- /bin/bash ./dev-tools/travis/travis-script.sh `pwd` $MODULES
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then echo TESTNUM $(find . -name TEST-*.xml
  -newer NOW | wc -l);        else echo TESTNUM $(find -name TEST-*.xml -newer NOW
  | wc -l);        fi
sudo: true
